services:
  plugin-js-sbom:
    build:
      context: ../../backend
      dockerfile: plugins/js-sbom/.cloud/docker/Dockerfile
      target: plugin-dev
      args:
        - PLUGINNAME=js-sbom
    image: codeclarityce/js-sbom-dev:latest
    restart: always
    volumes:
      - ../../backend:/codeclarity
      - ../../private:/private
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      pg_bouncer:
        condition: service_started
      adminer:
        condition: service_started
    env_file:
      - ../../.cloud/env/.env.dev

volumes:
  projects:
