package properties

const IMPORT_PATH_SEPERATOR = " > "
const VERSION_SEPERATOR = "@"
const DEFAULT_WORKSPACE_CHARACTER = "."
const SELF_MANAGED_WORKSPACES_CHARACTER = ".."
const OUTDATED_THRESHOLD = 6
const ORIGINAL_SCOPED_DELIMITER = "/"
const REPLACE_SCOPED_DELIMITER = ":"
