package versionType

type VERSION_TYPE string

const (
	RESOLVED_SEMVER                    VERSION_TYPE = "RESOLVED_SEMVER"
	UNRESOLVED_SEMVER                  VERSION_TYPE = "UNRESOLVED_SEMVER"
	COMMIT_ID_OR_BRANCH_OR_VERSION_TAG VERSION_TYPE = "COMMIT_ID_OR_BRANCH_OR_VERSION_TAG"
	HASH                               VERSION_TYPE = "HASH"
	UNKOWN_VERSION_TYPE                VERSION_TYPE = "UNKOWN"
)
